name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true
          recursive: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          hugo --minify
          touch public/.nojekyll  # Prevents GitHub Pages from using Jekyll

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/built-site
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git init
          git checkout --orphan gh-pages || git checkout gh-pages
          git add .
          git config user.name 'M-Hassan-Raza'
          git config user.email 'h.raza1164@yahoo.com'
          git commit -m 'Updated site' || echo "No changes to commit"
          git push --force origin gh-pages
